name:  Nueva Tarea
description: Crear una nueva tarea para el proyecto
title: "[TIPO]: "
labels: ["triage"]
body:
  - type: markdown
    attributes:
      value: |
        Gracias por crear una nueva tarea! Por favor completa los siguientes campos.
  - type: dropdown
    id: type
    attributes:
      label: Tipo de Tarea
      options:
        -  Dise帽o
        -  Setup
        -  Componente
        -  Secci贸n
        -  Animaci贸n
        -  Responsive
        -  Deploy
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Descripci贸n
      description: Describe detalladamente la tarea a realizar
    validations:
      required: true
  - type: textarea
    id: acceptance
    attributes:
      label: Criterios de Aceptaci贸n
      description: Lista los criterios que deben cumplirse para considerar la tarea completada
    validations:
      required: true
  - type: dropdown
    id: priority
    attributes:
      label: Prioridad
      options:
        -  Alta
        -  Media
        -  Baja
    validations:
      required: true
