name: Welcome First Time Contributors

on:
  pull_request_target:
    types: [opened]
  issues:
    types: [opened]

jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: "¡Gracias por crear tu primer issue! 🎉 Un miembro del equipo lo revisará pronto."
          pr-message: "¡Felicitaciones por tu primer pull request! 🚀 Revisaremos tus cambios lo antes posible."
